trigger:
- main  # Define the branch to trigger the pipeline (e.g., when changes are pushed to 'master')

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image for the build agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Specify the Node.js version you want to use
    checkLatest: true

- script: |
    # Install Node.js dependencies
    npm install

    # Building Node.js app
    npm run build

    # Testing Node.js app
    npm test

  displayName: 'Build Node.js App'

- task: PublishTestResults@2
  inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
# steps:
# - script: echo K8s Pipeline
#     displayName: 