trigger:
- main  # Define the branch to trigger the pipeline (e.g., when changes are pushed to 'master')

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image for the build agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Specify the Node.js version you want to use
    checkLatest: true

- script: |
    # Install Node.js dependencies
    npm install

    # Testing Node.js app
    npm test
  displayName: 'Test Node.js App'

# - script:
#     jest test --reporter jest-junit-reporter

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/test-results.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'guelmisdevops'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'guelmisdevops_testdevsuproject'
    cliProjectName: 'TestDevsuProject'
    cliSources: '.'
  displayName: 'SonarCloud Step 1'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'SonarCloud Step 2'
# steps:
# - script: echo K8s Pipeline
#     displayName: 