trigger:
- main  # Define the branch to trigger the pipeline (e.g., when changes are pushed to 'master')

pool:
  vmImage: 'ubuntu-latest'  # Specify the VM image for the build agent

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'  # Specify the Node.js version you want to use
    checkLatest: true

- script: |
    # Install Node.js dependencies
    npm install

    # Testing Node.js app
    npm test

  displayName: 'Test Node.js App'

- script: |
    npm install -g nyc
    nyc report --reporter=text-lcov > coverage.lcov
  displayName: 'Generate Code Coverage Report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage.lcov'
# steps:
# - script: echo K8s Pipeline
#     displayName: 